# Generated by Django 6.0.2 on 2026-02-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('физ', 'Физика'), ('инф', 'Информатика'), ('хим', 'Химия'), ('мат', 'Математика')], max_length=20, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Профиль', to='main.student'),
        ),
    ]
