# Generated by Django 6.0.2 on 2026-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='homework',
            field=models.TextField(blank=True, verbose_name='Домашнее задание'),
        ),
    ]
