# Generated by Django 6.0.2 on 2026-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_grade_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, verbose_name='Дни недели'),
        ),
    ]
