# Generated by Django 6.0.2 on 2026-02-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_days_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days_of_week',
        ),
    ]
