# Generated by Django 6.0.2 on 2026-03-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_course_days_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='student',
            new_name='user',
        ),
    ]
